rootProject.name = "TrenicalProj"
include("proto")
include("common-backend")
include("common-frontend")
include("railway-service")
include("admin-console")
include("train-service")
include("user-service")
include("customer-client")
include("ticketry-service")
include("promotionService")
include("gateway-service")
